# Generated by Django 3.2.7 on 2021-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('short_title', models.CharField(max_length=256)),
                ('nominal', models.IntegerField(choices=[(2, 2), (5, 5), (10, 10), (200000, 200000)])),
                ('series', models.CharField(max_length=256)),
                ('circulation', models.IntegerField()),
                ('metal', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('diameter', models.FloatField()),
                ('price', models.IntegerField()),
                ('existence', models.BooleanField(default=False)),
                ('obverse', models.ImageField(upload_to='coins_obverse')),
                ('reverse', models.ImageField(upload_to='coins_reverse')),
            ],
            options={
                'verbose_name': 'Coin',
            },
        ),
        migrations.AddConstraint(
            model_name='coin',
            constraint=models.UniqueConstraint(fields=('release_date', 'title'), name='coin_unique'),
        ),
        migrations.AddConstraint(
            model_name='coin',
            constraint=models.CheckConstraint(check=models.Q(('title__length__gt', 1)), name='coin_title_too_short'),
        ),
    ]
