version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db_${APP_NAME}
    hostname: db_${APP_NAME}
    ports:
      - "5429:5432"
    networks:
      - coins-net


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./coins_app/manage.py runserver 0.0.0.0:1488
    volumes:
      - .:/usr/src/app/
    ports:
      - "1488:1488"
    env_file: .env
    depends_on:
      - db
    hostname: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - coins-net

volumes:
    postgres_data:

networks:
  coins-net:
    driver: bridge
